Wait for the application to actually come up in 'riak start'
This allows you to see if riak is instantly crashing on startup instead
of silently failing.

diff --git a/rel/files/riak b/rel/files/riak
--- a/rel/files/riak
+++ b/rel/files/riak
@@ -78,6 +78,30 @@ case "$1" in
         mkdir -p $PIPE_DIR
         $ERTS_PATH/run_erl -daemon $PIPE_DIR/ $RUNNER_LOG_DIR \
             "exec $RUNNER_SCRIPT_DIR/$SCRIPT console" 2>&1
+
+        # Wait for the node to come up. We can't just ping it because
+        # distributed erlang comes up for a second before riak crashes
+        # (eg. in the case of an unwriteable disk). Once the node comes
+        # up we check for the node watcher process. If that's running
+        # then we assume things are good enough. This will at least let
+        # the user know when riak is crashing right after startup.
+        WAIT=${WAIT_FOR_ERLANG:-15}
+        while [ $WAIT -gt 0 ]; do
+            WAIT=$[$WAIT - 1]
+            sleep 1
+            RES=`$NODETOOL ping`
+            if [ "$?" -ne 0 ]; then
+                continue
+            fi
+            NODEWATCHER=`$NODETOOL rpcterms erlang whereis "'riak_core_node_watcher'."`
+            if [ "$NODEWATCHER" != "undefined" ]; then
+                exit 0
+            fi
+        done
+        echo "Riak failed to start within ${WAIT_FOR_ERLANG:-15} seconds."
+        echo "If you want to wait longer, set the environment variable"
+        echo "WAIT_FOR_ERLANG to the number of seconds to wait."
+        exit 1
         ;;
 
     stop)
